#!/usr/bin/env python

import sys
sys.path.append("/home/yoods/catkin_ws/src/rqt_param_manager/src")
from rqt_param_manager.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_param_manager'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))